# Site settings
title: gitops.ru

description: Открытый проект, где собираются материалы связанные с разработкой и развертыванием приложений

keywords: GitOps, Clouds, Linux, Docker, Kubernetes

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://gitops.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
