name: Mirror to GitLab

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_TOKEN@gitlab.com/$GITLAB_USERNAME/$GITLAB_REPONAME.git
          git push --mirror gitlab
        env:
          GITLAB_REPONAME: docs.gitops.ru
          GITLAB_USERNAME: webmakaka
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
